package com.definitelyscala.react

import scala.scalajs.js
import scala.scalajs.js.|

@js.native
trait HTMLAttributes[T] extends DOMAttributes[T] {
  // React-specific Attributes
  var defaultChecked: Boolean = js.native
  var defaultValue: String | js.Array[String] = js.native
  var suppressContentEditableWarning: Boolean = js.native
  // Standard HTML Attributes
  var accept: String = js.native
  var acceptCharset: String = js.native
  var accessKey: String = js.native
  var action: String = js.native
  var allowFullScreen: Boolean = js.native
  var allowTransparency: Boolean = js.native
  var alt: String = js.native
  var async: Boolean = js.native
  var autoComplete: String = js.native
  var autoFocus: Boolean = js.native
  var autoPlay: Boolean = js.native
  var capture: Boolean = js.native
  var cellPadding: Double | String = js.native
  var cellSpacing: Double | String = js.native
  var charSet: String = js.native
  var challenge: String = js.native
  var checked: Boolean = js.native
  var classID: String = js.native
  var className: String = js.native
  var cols: Double = js.native
  var colSpan: Double = js.native
  var content: String = js.native
  var contentEditable: Boolean = js.native
  var contextMenu: String = js.native
  var controls: Boolean = js.native
  var coords: String = js.native
  var crossOrigin: String = js.native
  var data: String = js.native
  var dateTime: String = js.native
  var default: Boolean = js.native
  var defer: Boolean = js.native
  var dir: String = js.native
  var disabled: Boolean = js.native
  var download: js.Any = js.native
  var draggable: Boolean = js.native
  var encType: String = js.native
  var form: String = js.native
  var formAction: String = js.native
  var formEncType: String = js.native
  var formMethod: String = js.native
  var formNoValidate: Boolean = js.native
  var formTarget: String = js.native
  var frameBorder: Double | String = js.native
  var headers: String = js.native
  var height: Double | String = js.native
  var hidden: Boolean = js.native
  var high: Double = js.native
  var href: String = js.native
  var hrefLang: String = js.native
  var htmlFor: String = js.native
  var httpEquiv: String = js.native
  var id: String = js.native
  var inputMode: String = js.native
  var integrity: String = js.native
  var is: String = js.native
  var keyParams: String = js.native
  var keyType: String = js.native
  var kind: String = js.native
  var label: String = js.native
  var lang: String = js.native
  var list: String = js.native
  var loop: Boolean = js.native
  var low: Double = js.native
  var manifest: String = js.native
  var marginHeight: Double = js.native
  var marginWidth: Double = js.native
  var max: Double | String = js.native
  var maxLength: Double = js.native
  var media: String = js.native
  var mediaGroup: String = js.native
  var method: String = js.native
  var min: Double | String = js.native
  var minLength: Double = js.native
  var multiple: Boolean = js.native
  var muted: Boolean = js.native
  var name: String = js.native
  var nonce: String = js.native
  var noValidate: Boolean = js.native
  var open: Boolean = js.native
  var optimum: Double = js.native
  var pattern: String = js.native
  var placeholder: String = js.native
  var playsInline: Boolean = js.native
  var poster: String = js.native
  var preload: String = js.native
  var radioGroup: String = js.native
  var readOnly: Boolean = js.native
  var rel: String = js.native
  var required: Boolean = js.native
  var reversed: Boolean = js.native
  var role: String = js.native
  var rows: Double = js.native
  var rowSpan: Double = js.native
  var sandbox: String = js.native
  var scope: String = js.native
  var scoped: Boolean = js.native
  var scrolling: String = js.native
  var seamless: Boolean = js.native
  var selected: Boolean = js.native
  var shape: String = js.native
  var size: Double = js.native
  var sizes: String = js.native
  var slot: String = js.native
  var span: Double = js.native
  var spellCheck: Boolean = js.native
  var src: String = js.native
  var srcDoc: String = js.native
  var srcLang: String = js.native
  var srcSet: String = js.native
  var start: Double = js.native
  var step: Double | String = js.native
  var style: CSSProperties = js.native
  var summary: String = js.native
  var tabIndex: Double = js.native
  var target: String = js.native
  var title: String = js.native
  var `type`: String = js.native
  var useMap: String = js.native
  var value: String | js.Array[String] | Double = js.native
  var width: Double | String = js.native
  var wmode: String = js.native
  var wrap: String = js.native
  // RDFa Attributes
  var about: String = js.native
  var datatype: String = js.native
  var inlist: js.Any = js.native
  var prefix: String = js.native
  var property: String = js.native
  var resource: String = js.native
  var typeof: String = js.native
  var vocab: String = js.native
  // Non-standard Attributes
  var autoCapitalize: String = js.native
  var autoCorrect: String = js.native
  var autoSave: String = js.native
  var color: String = js.native
  var itemProp: String = js.native
  var itemScope: Boolean = js.native
  var itemType: String = js.native
  var itemID: String = js.native
  var itemRef: String = js.native
  var results: Double = js.native
  var security: String = js.native
  var unselectable: Boolean = js.native
}