package com.definitelyscala.react

import scala.scalajs.js
import scala.scalajs.js.|

@js.native
trait SVGAttributes[T] extends DOMAttributes[T] {
  // Attributes which also defined in HTMLAttributes
  // See comment in SVGDOMPropertyConfig.js
  var className: String = js.native
  var color: String = js.native
  var height: Double | String = js.native
  var id: String = js.native
  var lang: String = js.native
  var max: Double | String = js.native
  var media: String = js.native
  var method: String = js.native
  var min: Double | String = js.native
  var name: String = js.native
  var style: CSSProperties = js.native
  var target: String = js.native
  var `type`: String = js.native
  var width: Double | String = js.native
  // SVG Specific attributes
  var accentHeight: Double | String = js.native
  var accumulate: String | String = js.native
  var additive: String | String = js.native
  var alignmentBaseline: String | String | String | String | String | String | String | String | String | String | String | String | String = js.native
  var allowReorder: String | String = js.native
  var alphabetic: Double | String = js.native
  var amplitude: Double | String = js.native
  var arabicForm: String | String | String | String = js.native
  var ascent: Double | String = js.native
  var attributeName: String = js.native
  var attributeType: String = js.native
  var autoReverse: Double | String = js.native
  var azimuth: Double | String = js.native
  var baseFrequency: Double | String = js.native
  var baselineShift: Double | String = js.native
  var baseProfile: Double | String = js.native
  var bbox: Double | String = js.native
  var begin: Double | String = js.native
  var bias: Double | String = js.native
  var by: Double | String = js.native
  var calcMode: Double | String = js.native
  var capHeight: Double | String = js.native
  var clip: Double | String = js.native
  var clipPath: String = js.native
  var clipPathUnits: Double | String = js.native
  var clipRule: Double | String = js.native
  var colorInterpolation: Double | String = js.native
  var colorInterpolationFilters: String | String | String | String = js.native
  var colorProfile: Double | String = js.native
  var colorRendering: Double | String = js.native
  var contentScriptType: Double | String = js.native
  var contentStyleType: Double | String = js.native
  var cursor: Double | String = js.native
  var cx: Double | String = js.native
  var cy: Double | String = js.native
  var d: String = js.native
  var decelerate: Double | String = js.native
  var descent: Double | String = js.native
  var diffuseConstant: Double | String = js.native
  var direction: Double | String = js.native
  var display: Double | String = js.native
  var divisor: Double | String = js.native
  var dominantBaseline: Double | String = js.native
  var dur: Double | String = js.native
  var dx: Double | String = js.native
  var dy: Double | String = js.native
  var edgeMode: Double | String = js.native
  var elevation: Double | String = js.native
  var enableBackground: Double | String = js.native
  var end: Double | String = js.native
  var exponent: Double | String = js.native
  var externalResourcesRequired: Double | String = js.native
  var fill: String = js.native
  var fillOpacity: Double | String = js.native
  var fillRule: String | String | String = js.native
  var filter: String = js.native
  var filterRes: Double | String = js.native
  var filterUnits: Double | String = js.native
  var floodColor: Double | String = js.native
  var floodOpacity: Double | String = js.native
  var focusable: Double | String = js.native
  var fontFamily: String = js.native
  var fontSize: Double | String = js.native
  var fontSizeAdjust: Double | String = js.native
  var fontStretch: Double | String = js.native
  var fontStyle: Double | String = js.native
  var fontVariant: Double | String = js.native
  var fontWeight: Double | String = js.native
  var format: Double | String = js.native
  var from: Double | String = js.native
  var fx: Double | String = js.native
  var fy: Double | String = js.native
  var g1: Double | String = js.native
  var g2: Double | String = js.native
  var glyphName: Double | String = js.native
  var glyphOrientationHorizontal: Double | String = js.native
  var glyphOrientationVertical: Double | String = js.native
  var glyphRef: Double | String = js.native
  var gradientTransform: String = js.native
  var gradientUnits: String = js.native
  var hanging: Double | String = js.native
  var horizAdvX: Double | String = js.native
  var horizOriginX: Double | String = js.native
  var ideographic: Double | String = js.native
  var imageRendering: Double | String = js.native
  var in2: Double | String = js.native
  var in: String = js.native
  var intercept: Double | String = js.native
  var k1: Double | String = js.native
  var k2: Double | String = js.native
  var k3: Double | String = js.native
  var k4: Double | String = js.native
  var k: Double | String = js.native
  var kernelMatrix: Double | String = js.native
  var kernelUnitLength: Double | String = js.native
  var kerning: Double | String = js.native
  var keyPoints: Double | String = js.native
  var keySplines: Double | String = js.native
  var keyTimes: Double | String = js.native
  var lengthAdjust: Double | String = js.native
  var letterSpacing: Double | String = js.native
  var lightingColor: Double | String = js.native
  var limitingConeAngle: Double | String = js.native
  var local: Double | String = js.native
  var markerEnd: String = js.native
  var markerHeight: Double | String = js.native
  var markerMid: String = js.native
  var markerStart: String = js.native
  var markerUnits: Double | String = js.native
  var markerWidth: Double | String = js.native
  var mask: String = js.native
  var maskContentUnits: Double | String = js.native
  var maskUnits: Double | String = js.native
  var mathematical: Double | String = js.native
  var mode: Double | String = js.native
  var numOctaves: Double | String = js.native
  var offset: Double | String = js.native
  var opacity: Double | String = js.native
  var operator: Double | String = js.native
  var order: Double | String = js.native
  var orient: Double | String = js.native
  var orientation: Double | String = js.native
  var origin: Double | String = js.native
  var overflow: Double | String = js.native
  var overlinePosition: Double | String = js.native
  var overlineThickness: Double | String = js.native
  var paintOrder: Double | String = js.native
  var panose1: Double | String = js.native
  var pathLength: Double | String = js.native
  var patternContentUnits: String = js.native
  var patternTransform: Double | String = js.native
  var patternUnits: String = js.native
  var pointerEvents: Double | String = js.native
  var points: String = js.native
  var pointsAtX: Double | String = js.native
  var pointsAtY: Double | String = js.native
  var pointsAtZ: Double | String = js.native
  var preserveAlpha: Double | String = js.native
  var preserveAspectRatio: String = js.native
  var primitiveUnits: Double | String = js.native
  var r: Double | String = js.native
  var radius: Double | String = js.native
  var refX: Double | String = js.native
  var refY: Double | String = js.native
  var renderingIntent: Double | String = js.native
  var repeatCount: Double | String = js.native
  var repeatDur: Double | String = js.native
  var requiredExtensions: Double | String = js.native
  var requiredFeatures: Double | String = js.native
  var restart: Double | String = js.native
  var result: String = js.native
  var rotate: Double | String = js.native
  var rx: Double | String = js.native
  var ry: Double | String = js.native
  var scale: Double | String = js.native
  var seed: Double | String = js.native
  var shapeRendering: Double | String = js.native
  var slope: Double | String = js.native
  var spacing: Double | String = js.native
  var specularConstant: Double | String = js.native
  var specularExponent: Double | String = js.native
  var speed: Double | String = js.native
  var spreadMethod: String = js.native
  var startOffset: Double | String = js.native
  var stdDeviation: Double | String = js.native
  var stemh: Double | String = js.native
  var stemv: Double | String = js.native
  var stitchTiles: Double | String = js.native
  var stopColor: String = js.native
  var stopOpacity: Double | String = js.native
  var strikethroughPosition: Double | String = js.native
  var strikethroughThickness: Double | String = js.native
  var string: Double | String = js.native
  var stroke: String = js.native
  var strokeDasharray: String | Double = js.native
  var strokeDashoffset: String | Double = js.native
  var strokeLinecap: String | String | String | String = js.native
  var strokeLinejoin: String | String | String | String = js.native
  var strokeMiterlimit: String = js.native
  var strokeOpacity: Double | String = js.native
  var strokeWidth: Double | String = js.native
  var surfaceScale: Double | String = js.native
  var systemLanguage: Double | String = js.native
  var tableValues: Double | String = js.native
  var targetX: Double | String = js.native
  var targetY: Double | String = js.native
  var textAnchor: String = js.native
  var textDecoration: Double | String = js.native
  var textLength: Double | String = js.native
  var textRendering: Double | String = js.native
  var to: Double | String = js.native
  var transform: String = js.native
  var u1: Double | String = js.native
  var u2: Double | String = js.native
  var underlinePosition: Double | String = js.native
  var underlineThickness: Double | String = js.native
  var unicode: Double | String = js.native
  var unicodeBidi: Double | String = js.native
  var unicodeRange: Double | String = js.native
  var unitsPerEm: Double | String = js.native
  var vAlphabetic: Double | String = js.native
  var values: String = js.native
  var vectorEffect: Double | String = js.native
  var version: String = js.native
  var vertAdvY: Double | String = js.native
  var vertOriginX: Double | String = js.native
  var vertOriginY: Double | String = js.native
  var vHanging: Double | String = js.native
  var vIdeographic: Double | String = js.native
  var viewBox: String = js.native
  var viewTarget: Double | String = js.native
  var visibility: Double | String = js.native
  var vMathematical: Double | String = js.native
  var widths: Double | String = js.native
  var wordSpacing: Double | String = js.native
  var writingMode: Double | String = js.native
  var x1: Double | String = js.native
  var x2: Double | String = js.native
  var x: Double | String = js.native
  var xChannelSelector: String = js.native
  var xHeight: Double | String = js.native
  var xlinkActuate: String = js.native
  var xlinkArcrole: String = js.native
  var xlinkHref: String = js.native
  var xlinkRole: String = js.native
  var xlinkShow: String = js.native
  var xlinkTitle: String = js.native
  var xlinkType: String = js.native
  var xmlBase: String = js.native
  var xmlLang: String = js.native
  var xmlns: String = js.native
  var xmlnsXlink: String = js.native
  var xmlSpace: String = js.native
  var y1: Double | String = js.native
  var y2: Double | String = js.native
  var y: Double | String = js.native
  var yChannelSelector: String = js.native
  var z: Double | String = js.native
  var zoomAndPan: String = js.native
}